### ISSUE TITLE
Feature request: subcommands

### ISSUE THREAD

**Issue by emmatebibyte** [DoumanAsh/arg.rs#4]
It would be cool to have support for non-opt subcommands that don't have dashes before them. Would this be possible/in scope for this crate?
```rs
#[derive(Args, Debug)]
struct Arguments {
  argv0: String,

  #[arg(subcommand)]
  get: Vec<String>,
}
```
and then `argv0 get string1 string2 string3` gives you:
```rs
Arguments.argv0 == "argv0";
Arguments.get == [ "string1", "string2", "string3" ]
```

**Comment by DoumanAsh** [comment]
Yes, it should be possible, but I'm just utterly lazy to do it as I mostly dislike using sub-commands.
Still it is nice feature to have so I'll find time to implement logic in code generator for that

Ideally sub command should work like that:

```rust
#[derive(Args, Debug)]
pub enum Subcommand {
    Argv0(MyCommand)
}

#[derive(Args, Debug)]
struct Arguments {
    #[arg(subcommand)]
    sub: Subcommand
}
```

**Comment by emmatebibyte** [comment]
So if my program has a subcommand `get`, which can be passed an arbitrary number of strings and optional opts, it would work like this?
```rs
#[derive(Args, Debug)]
pub enum Subcommand {
    get(Vec<String>, Option<<Vec<String>>)
}

#[derive(Args, Debug)]
struct Arguments {
    #[arg(subcommand)]
    sub: Subcommand
}
```

**Comment by DoumanAsh** [comment]
yeah that's my idea

**Comment by emmatebibyte** [comment]
Thank you so much :)

**Comment by DoumanAsh** [comment]
I made breaking change version `0.4.0` with sub-command for both derive and main crate
