### ISSUE TITLE
Options in quotes are picked up as options

### ISSUE THREAD

**Issue by emmatebibyte** [DoumanAsh/arg.rs#6]
this command passes `-n` to `tail` even though it should not:
```
$ target/x86_64-unknown-linux-gnu/release/tail '-n' +2 Cargo.toml
[package]
name = "coreutils"
```

**Comment by DoumanAsh** [comment]
I'm not sure I follow what should happen?

Quotes are not stripped by this parser (unless you use https://docs.rs/arg/0.3.1/arg/trait.Args.html#method.from_text which extracts options on quote basis
i.e. you should strip quotes from `Iterator` yourself when passing it as `Iterator` or concatenate it into one string

**Comment by DoumanAsh** [comment]
or maybe just `args.iter().map(|arg| arg.strip_matches('\''))`?

But you should make sure to check how your shell passes arguments in this case.
Depending on shell quotation may behave differently

**Comment by emmatebibyte** [comment]
The program acts like `-n` was specified when `'-n'` was what was passed

**Comment by DoumanAsh** [comment]
well then it means your shell strips quotes.
`args` does nothing of sort.
I cannot fix how your shell passes arguments.
Quotes are used to allow you to encode variables or white spaces into arguments, they are not passed as it is
