### ISSUE TITLE
Clarify what "No dependencies" means

### ISSUE THREAD

**Issue by ghost** [DoumanAsh/arg.rs#8]
Hello,

I was excited to see an arg parser with "No dependencies", and confused to see that it does indeed have 6 dependencies as shown by `cargo tree`:

```
prj v0.1.0 (/home/sam/prj)
└── arg v0.4.1
    └── arg-derive v0.4.1 (proc-macro)
        ├── quote v1.0.23
        │   └── proc-macro2 v1.0.51
        │       └── unicode-ident v1.0.6
        ├── syn v1.0.109
        │   ├── proc-macro2 v1.0.51 (*)
        │   ├── quote v1.0.23 (*)
        │   └── unicode-ident v1.0.6
        └── tabwriter v1.2.1
            └── unicode-width v0.1.10
```

I suspect these maybe compile time dependencies, and the claim should actually be "No runtime dependencies" - is it reasonable to update the README with that ?

Sorry for the pedantry BTW, there are situations where *all* external dependencies need to be accounted for, so I am sensitive to this distinction :)

**Comment by DoumanAsh** [comment]
Ah yeah, unfortunately there are compile time dependencies.
But most of the time overhead (as if code size increase) come from runtime dependencies.
After all your final executable is not linked with build script, hence I never thought of build dependencies as actual dependencies
I suppose I can just add correction to README, but AFAIK from legal point of view only runtime dependencies have implications on licensing as you only include runtime dependencies code inside your binary/library.
Build time dependencies are not included into final product hence they cannot have legal implications

**Comment by DoumanAsh** [comment]
I added clarification to README https://github.com/DoumanAsh/arg.rs/commit/5b9ef3d0c802c981769d2e0b47396e164a115b01

Sorry about confusion, but be sure that you can ignore build time dependencies always as they have no harmful impact on final binary

**Comment by ghost** [comment]
Ah nice, thanks for the quick response!
